GET http://localhost:8080/queryOrder/1


###
POST http://localhost:8080/createOrder
Content-Type: application/json

{
  "orderNumber": "0001",
  "score": "4"
}
###
POST http://localhost:8080/register/member


###
POST http://localhost:8080/register/sender
Content-Type: application/json

{
  "username": "111",
  "password": "222"

}

###
